// <auto-generated> by tools/codegen/gen_items.py from reference/data/items.json and
// reference/data/creative_tabs.json (values evaluated from the running reference main.js). Do not edit.
namespace BlockcraftPort
{
    /// <summary>main.js Gn[] items (numeric ids from ItemIdBase). Port item keys are the texture names.</summary>
    public static class SourceItemData
    {
        public const int ItemIdBase = 2000;
        public const int Count = 130;
        public static readonly string[] Key = new string[]
        {
            "STICK","COAL","IRON_INGOT","GOLD_INGOT","DIAMOND_GEM","EMERALD_GEM",
            "FLINT","SUGAR","APPLE","SWEET_BERRIES_ITEM","MELON_SLICE","PORKCHOP",
            "COOKED_PORKCHOP","BEEF","COOKED_BEEF","MUTTON","COOKED_MUTTON","CHICKEN_RAW",
            "COOKED_CHICKEN","ROTTEN_FLESH","FEATHER","LEATHER","BONE","GUNPOWDER",
            "ARROW","SPAWN_EGG_PIG","SPAWN_EGG_COW","SPAWN_EGG_SHEEP","SPAWN_EGG_CHICKEN","SPAWN_EGG_ZOMBIE",
            "SPAWN_EGG_SKELETON","SPAWN_EGG_CREEPER","WOODEN_PICKAXE","WOODEN_AXE","WOODEN_SHOVEL","WOODEN_SWORD",
            "STONE_PICKAXE","STONE_AXE","STONE_SHOVEL","STONE_SWORD","IRON_PICKAXE","IRON_AXE",
            "IRON_SHOVEL","IRON_SWORD","GOLDEN_PICKAXE","GOLDEN_AXE","GOLDEN_SHOVEL","GOLDEN_SWORD",
            "DIAMOND_PICKAXE","DIAMOND_AXE","DIAMOND_SHOVEL","DIAMOND_SWORD","BOW","WHEAT",
            "WHEAT_SEEDS","BREAD","WOODEN_HOE","STONE_HOE","IRON_HOE","GOLDEN_HOE",
            "DIAMOND_HOE","BUCKET","WATER_BUCKET","LAVA_BUCKET","CARROT","POTATO",
            "BAKED_POTATO","GOLDEN_APPLE","GOLDEN_CARROT","BOWL","MUSHROOM_STEW","BONE_MEAL",
            "SHEARS","LEATHER_HELMET","LEATHER_CHESTPLATE","LEATHER_LEGGINGS","LEATHER_BOOTS","IRON_HELMET",
            "IRON_CHESTPLATE","IRON_LEGGINGS","IRON_BOOTS","GOLDEN_HELMET","GOLDEN_CHESTPLATE","GOLDEN_LEGGINGS",
            "GOLDEN_BOOTS","DIAMOND_HELMET","DIAMOND_CHESTPLATE","DIAMOND_LEGGINGS","DIAMOND_BOOTS","PUMPKIN_SEEDS",
            "MELON_SEEDS","RAW_COPPER","COPPER_INGOT","WHITE_DYE","ORANGE_DYE","MAGENTA_DYE",
            "LIGHT_BLUE_DYE","YELLOW_DYE","LIME_DYE","PINK_DYE","GRAY_DYE","LIGHT_GRAY_DYE",
            "CYAN_DYE","PURPLE_DYE","BLUE_DYE","BROWN_DYE","GREEN_DYE","RED_DYE",
            "BLACK_DYE","CLAY_BALL","BRICK","MINECART","BOAT","STRING",
            "FISHING_ROD","RAW_COD","COOKED_COD","RAW_SALMON","COOKED_SALMON","SPIDER_EYE",
            "ENDER_PEARL","SLIME_BALL","SPAWN_EGG_SPIDER","SPAWN_EGG_ENDERMAN","SPAWN_EGG_SALMON","SPAWN_EGG_SLIME",
            "SPAWN_EGG_SHARK","EGG","PUMPKIN_PIE","SHIP_SPAWNER",
        };
        /// <summary>Port inventory item key (main.js tex).</summary>
        public static readonly string[] Tex = new string[]
        {
            "item_stick","item_coal","item_iron_ingot","item_gold_ingot","item_diamond","item_emerald",
            "item_flint","item_sugar","item_apple","item_sweet_berries","item_melon_slice","item_porkchop",
            "item_cooked_porkchop","item_beef","item_cooked_beef","item_mutton","item_cooked_mutton","item_chicken",
            "item_cooked_chicken","item_rotten_flesh","item_feather","item_leather","item_bone","item_gunpowder",
            "item_arrow","item_spawn_egg","item_spawn_egg","item_spawn_egg","item_spawn_egg","item_spawn_egg",
            "item_spawn_egg","item_spawn_egg","item_wooden_pickaxe","item_wooden_axe","item_wooden_shovel","item_wooden_sword",
            "item_stone_pickaxe","item_stone_axe","item_stone_shovel","item_stone_sword","item_iron_pickaxe","item_iron_axe",
            "item_iron_shovel","item_iron_sword","item_golden_pickaxe","item_golden_axe","item_golden_shovel","item_golden_sword",
            "item_diamond_pickaxe","item_diamond_axe","item_diamond_shovel","item_diamond_sword","item_bow","item_wheat",
            "item_wheat_seeds","item_bread","item_wooden_hoe","item_stone_hoe","item_iron_hoe","item_golden_hoe",
            "item_diamond_hoe","item_bucket","item_water_bucket","item_lava_bucket","item_carrot","item_potato",
            "item_baked_potato","item_golden_apple","item_golden_carrot","item_bowl","item_mushroom_stew","item_bone_meal",
            "item_shears","item_leather_helmet","item_leather_chestplate","item_leather_leggings","item_leather_boots","item_iron_helmet",
            "item_iron_chestplate","item_iron_leggings","item_iron_boots","item_golden_helmet","item_golden_chestplate","item_golden_leggings",
            "item_golden_boots","item_diamond_helmet","item_diamond_chestplate","item_diamond_leggings","item_diamond_boots","item_pumpkin_seeds",
            "item_melon_seeds","item_raw_copper","item_copper_ingot","item_white_dye","item_orange_dye","item_magenta_dye",
            "item_light_blue_dye","item_yellow_dye","item_lime_dye","item_pink_dye","item_gray_dye","item_light_gray_dye",
            "item_cyan_dye","item_purple_dye","item_blue_dye","item_brown_dye","item_green_dye","item_red_dye",
            "item_black_dye","item_clay_ball","item_brick","item_minecart","item_boat","item_string",
            "item_fishing_rod","item_raw_cod","item_cooked_cod","item_raw_salmon","item_cooked_salmon","item_spider_eye",
            "item_ender_pearl","item_slime_ball","item_spawn_egg","item_spawn_egg","item_spawn_egg","item_spawn_egg",
            "item_spawn_egg","item_egg","item_pumpkin_pie","item_ship",
        };
        public static readonly string[] NameEn = new string[]
        {
            "Stick","Coal","Iron Ingot","Gold Ingot","Diamond","Emerald",
            "Flint","Sugar","Apple","Sweet Berries","Melon Slice","Raw Porkchop",
            "Cooked Porkchop","Raw Beef","Steak","Raw Mutton","Cooked Mutton","Raw Chicken",
            "Cooked Chicken","Rotten Flesh","Feather","Leather","Bone","Gunpowder",
            "Arrow","Pig Spawn Egg","Cow Spawn Egg","Sheep Spawn Egg","Chicken Spawn Egg","Zombie Spawn Egg",
            "Skeleton Spawn Egg","Creeper Spawn Egg","Wooden Pickaxe","Wooden Axe","Wooden Shovel","Wooden Sword",
            "Stone Pickaxe","Stone Axe","Stone Shovel","Stone Sword","Iron Pickaxe","Iron Axe",
            "Iron Shovel","Iron Sword","Golden Pickaxe","Golden Axe","Golden Shovel","Golden Sword",
            "Diamond Pickaxe","Diamond Axe","Diamond Shovel","Diamond Sword","Bow","Wheat",
            "Wheat Seeds","Bread","Wooden Hoe","Stone Hoe","Iron Hoe","Golden Hoe",
            "Diamond Hoe","Bucket","Water Bucket","Lava Bucket","Carrot","Potato",
            "Baked Potato","Golden Apple","Golden Carrot","Bowl","Mushroom Stew","Bone Meal",
            "Shears","Leather Helmet","Leather Chestplate","Leather Leggings","Leather Boots","Iron Helmet",
            "Iron Chestplate","Iron Leggings","Iron Boots","Golden Helmet","Golden Chestplate","Golden Leggings",
            "Golden Boots","Diamond Helmet","Diamond Chestplate","Diamond Leggings","Diamond Boots","Pumpkin Seeds",
            "Melon Seeds","Raw Copper","Copper Ingot","White Dye","Orange Dye","Magenta Dye",
            "Light Blue Dye","Yellow Dye","Lime Dye","Pink Dye","Gray Dye","Light Gray Dye",
            "Cyan Dye","Purple Dye","Blue Dye","Brown Dye","Green Dye","Red Dye",
            "Black Dye","Clay Ball","Brick","Minecart","Boat","String",
            "Fishing Rod","Raw Cod","Cooked Cod","Raw Salmon","Cooked Salmon","Spider Eye",
            "Ender Pearl","Slimeball","Spider Spawn Egg","Enderman Spawn Egg","Salmon Spawn Egg","Slime Spawn Egg",
            "Shark Spawn Egg","Egg","Pumpkin Pie","Ship",
        };
        public static readonly string[] NameRu = new string[]
        {
            "Палка","Уголь","Железный слиток","Золотой слиток","Алмаз","Изумруд",
            "Кремень","Сахар","Яблоко","Сладкие ягоды","Ломтик арбуза","Сырая свинина",
            "Жареная свинина","Сырая говядина","Стейк","Сырая баранина","Жареная баранина","Сырая курятина",
            "Жареная курятина","Гнилая плоть","Перо","Кожа","Кость","Порох",
            "Стрела","Яйцо призыва: свинья","Яйцо призыва: корова","Яйцо призыва: овца","Яйцо призыва: курица","Яйцо призыва: зомби",
            "Яйцо призыва: скелет","Яйцо призыва: крипер","Деревянная кирка","Деревянный топор","Деревянная лопата","Деревянный меч",
            "Каменная кирка","Каменный топор","Каменная лопата","Каменный меч","Железная кирка","Железный топор",
            "Железная лопата","Железный меч","Золотая кирка","Золотой топор","Золотая лопата","Золотой меч",
            "Алмазная кирка","Алмазный топор","Алмазная лопата","Алмазный меч","Лук","Пшеница",
            "Семена пшеницы","Хлеб","Деревянная мотыга","Каменная мотыга","Железная мотыга","Золотая мотыга",
            "Алмазная мотыга","Ведро","Ведро воды","Ведро лавы","Морковь","Картофель",
            "Печёный картофель","Золотое яблоко","Золотая морковь","Миска","Грибной суп","Костная мука",
            "Ножницы","Кожаный шлем","Кожаная куртка","Кожаные штаны","Кожаные ботинки","Железный шлем",
            "Железный нагрудник","Железные поножи","Железные ботинки","Золотой шлем","Золотой нагрудник","Золотые поножи",
            "Золотые ботинки","Алмазный шлем","Алмазный нагрудник","Алмазные поножи","Алмазные ботинки","Семена тыквы",
            "Семена арбуза","Необработанная медь","Медный слиток","Краситель: белый","Краситель: оранжевый","Краситель: сиреневый",
            "Краситель: голубой","Краситель: жёлтый","Краситель: лаймовый","Краситель: розовый","Краситель: серый","Краситель: светло-серый",
            "Краситель: бирюзовый","Краситель: фиолетовый","Краситель: синий","Краситель: коричневый","Краситель: зелёный","Краситель: красный",
            "Краситель: чёрный","Глиняный шарик","Кирпич","Вагонетка","Лодка","Нить",
            "Удочка","Сырая треска","Жареная треска","Сырой лосось","Жареный лосось","Паучий глаз",
            "Жемчуг Эндера","Слизь","Яйцо призыва: паук","Яйцо призыва: эндермен","Яйцо призыва: лосось","Яйцо призыва: слизень",
            "Яйцо призыва: акула","Яйцо","Тыквенный пирог","Корабль",
        };
        /// <summary>Tile index of the item icon in the reference block atlas (main.js M[id].icon).</summary>
        public static readonly short[] IconTile = new short[]
        {
            602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,
            622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,
            642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,
            662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,
            682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,
            702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,719,720,721,722,723,
            724,725,726,727,728,729,730,731,732,734,
        };
        public static readonly byte[] Stack = new byte[]
        {
            64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,
            64,64,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,64,64,64,1,1,1,1,
            1,16,1,1,64,64,64,64,64,64,1,64,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,64,
            64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,1,1,64,1,64,64,64,64,64,
            16,64,64,64,64,64,64,16,64,1,
        };
        static System.Collections.Generic.Dictionary<string, int> byTex;
        /// <summary>Index into the tables for a port item key, or -1.</summary>
        public static int IndexOfTex(string tex)
        {
            if (tex == null) return -1;
            if (byTex == null)
            {
                var d = new System.Collections.Generic.Dictionary<string, int>(Count);
                for (int i = 0; i < Count; i++) d[Tex[i]] = i;
                byTex = d;
            }
            return byTex.TryGetValue(tex, out int v) ? v : -1;
        }
    }

    /// <summary>main.js uo[]: creative inventory tabs with their exact entry order (reference numeric ids).</summary>
    public static class SourceCreativeTabs
    {
        public const int Count = 9;
        public static readonly string[] Key = { "building", "colored", "natural", "functional", "tools", "combat", "food", "ingredients", "eggs" };
        public static readonly string[] NameEn = { "Building Blocks", "Colored Blocks", "Natural Blocks", "Functional Blocks", "Tools & Utilities", "Combat", "Food & Drinks", "Ingredients", "Spawn Eggs" };
        public static readonly string[] NameRu = { "Строительные блоки", "Цветные блоки", "Природные блоки", "Функциональные блоки", "Инструменты", "Бой", "Еда и напитки", "Материалы", "Яйца призыва" };
        /// <summary>main eL: tabs shown in the top row (the rest are in the bottom row).</summary>
        public static readonly bool[] Top = { true, true, true, true, false, false, false, false, false };
        /// <summary>main rL(): reference id drawn on each tab button.</summary>
        public static readonly int[] IconSourceId = { 12, 142, 1, 392, 2048, 2051, 2067, 2002, 2031 };
        public static readonly int[][] Entries =
        {
            new int[]
            {
                3,4,21,9,41,42,12,60,61,62,63,64,65,66,67,68,69,70,74,75,
                77,78,79,80,81,82,83,84,85,87,88,89,24,207,208,209,210,211,212,213,
                214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,
                234,235,236,237,238,239,240,241,338,339,340,341,342,343,344,345,346,347,348,349,
                394,396,398,400,402,404,406,408,410,412,414,416,418,420,422,424,426,428,430,432,
                434,436,438,440,442,444,446,448,450,452,454,456,458,460,462,464,466,468,555,558,
                561,563,565,395,397,399,401,403,405,407,409,411,413,415,417,419,421,423,425,427,
                429,431,433,435,437,439,441,443,445,447,449,451,453,455,457,459,461,463,465,467,
                469,556,559,562,564,566,470,471,472,473,474,475,476,477,478,479,480,481,482,483,
                484,485,486,487,488,489,490,491,492,557,560,525,542,543,544,545,546,547,548,549,
                550,551,552,553,554,
            },
            new int[]
            {
                26,28,29,30,31,32,27,33,94,95,96,97,98,99,100,101,102,103,104,105,
                106,107,108,109,56,57,58,136,137,138,139,140,141,142,143,144,145,146,147,148,
                149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,
                169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,
                189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,526,527,
                528,529,530,531,532,533,534,535,536,537,538,539,540,541,508,509,510,511,512,513,
                514,515,516,517,518,519,520,521,522,523,
            },
            new int[]
            {
                1,2,54,5,55,6,90,15,13,14,91,92,22,16,11,93,71,76,86,72,
                73,17,18,19,20,7,8,37,38,39,40,48,49,50,51,52,53,43,242,243,
                244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,
                264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,
                284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,
                304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,
                324,325,326,327,328,329,330,331,332,333,334,335,336,337,643,648,524,44,59,45,
                46,47,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,
                368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,
                388,389,390,599,600,601,602,603,604,605,606,607,608,609,
            },
            new int[]
            {
                10,23,25,392,393,642,110,111,112,113,114,115,610,612,614,616,618,620,622,624,
                626,628,630,632,634,636,638,640,116,117,118,119,120,121,122,123,124,493,495,497,
                499,501,503,505,507,125,126,127,494,496,498,500,502,504,506,567,568,569,570,571,
                572,573,574,575,576,577,578,128,129,130,579,580,581,582,583,584,585,586,587,588,
                131,132,133,589,590,591,592,593,594,595,596,597,598,134,135,673,670,671,391,672,
            },
            new int[]
            {
                391,2032,2033,2034,2036,2037,2038,2040,2041,2042,2044,2045,2046,2048,2049,2050,2056,2057,2058,2059,
                2060,2061,2062,2063,2072,2111,2112,2114,2129,
            },
            new int[]
            {
                25,2024,2033,2035,2037,2039,2041,2043,2045,2047,2049,2051,2052,2073,2074,2075,2076,2077,2078,2079,
                2080,2081,2082,2083,2084,2085,2086,2087,2088,
            },
            new int[]
            {
                2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2055,2064,2065,2066,2067,2068,2070,2115,
                2116,2117,2118,2128,
            },
            new int[]
            {
                2000,2001,2002,2003,2004,2005,2006,2007,2020,2021,2022,2023,2024,2053,2054,2069,2071,2089,2090,2091,
                2092,2093,2094,2095,2096,2097,2098,2099,2100,2101,2102,2103,2104,2105,2106,2107,2108,2109,2110,2113,
                2119,2120,2121,2127,
            },
            new int[]
            {
                2025,2026,2027,2028,2029,2030,2031,2122,2123,2124,2125,2126,
            },
        };
    }
}
