// Differential test corpus: every case runs as plain JS and as compiled WASM;
// the logged output must be identical. log()/logError() are host functions.
export const cases = {
  // ---------- variables and scopes ----------
  'var hoisting': `log(typeof a, a); var a = 1; log(a); function f(){ log(b); var b = 2; return b; } log(f());`,
  'let/const block scope': `let x = 1; { let x = 2; log(x); { const x = 3; log(x); } log(x); } log(x);`,
  'tdz error': `try { log(y); let y = 1; } catch (e) { logError(e); } try { (function(){ z = 2; let z; })(); } catch (e) { logError(e); }`,
  'tdz in closure': `function f(){ const g = () => v; try { g(); } catch (e) { logError(e); } let v = 5; return g(); } log(f());`,
  'const assignment': `const c = 1; try { c = 2; } catch (e) { logError(e); } log(c); try { (function(){ const k = 1; k++; })(); } catch (e) { logError(e); }`,
  'closures counter': `function counter(){ let n = 0; return { inc: () => ++n, get: () => n }; } const a = counter(), b = counter(); a.inc(); a.inc(); b.inc(); log(a.get(), b.get());`,
  'closure over loop let': `const fs = []; for (let i = 0; i < 3; i++) fs.push(() => i); log(fs.map(f => f()).join());`,
  'closure over loop var': `const fs = []; for (var i = 0; i < 3; i++) fs.push(() => i); log(fs.map(f => f()).join());`,
  'loop let mutated in body': `const fs = []; for (let i = 0; i < 6; i++) { fs.push(() => i); i++; } log(fs.map(f => f()).join());`,
  'closure modifies outer': `let total = 0; function add(n){ total += n; } [1,2,3].forEach(add); log(total);`,
  'nested closures': `function a(x){ return function b(y){ return function c(z){ return x + y + z; }; }; } log(a(1)(2)(3)); function m(){ let s = 0; for (let i = 0; i < 3; i++) { let j = i * 2; (() => { s += j; })(); } return s; } log(m());`,
  'shadowing params': `function f(a, b = a + 1){ { let a = 10; log(a, b); } return a; } log(f(1)); log(f(1, 5));`,
  'default params scope': `let x = 'outer'; function f(a = x){ let x = 'inner'; return a; } log(f());`,
  'default param closure': `function f(a, g = () => a){ var a = 2; return [a, g()]; } log(f(1));`,
  'function declarations hoisted': `log(h()); function h(){ return 'h'; } log(typeof k); var k = function(){};`,
  'named function expression': `const f = function fact(n){ return n <= 1 ? 1 : n * fact(n - 1); }; log(f(5)); log(typeof fact);`,
  'named fe binding immutable': `const f = function g(){ g = 1; return typeof g; }; log(f()); const h = function g(){ 'use strict'; try { g = 1; } catch (e) { logError(e); } return typeof g; }; log(h());`,
  'global var on window': `var gv = 5; log(window.gv); window.gv = 6; log(gv); function gf(){} log(typeof window.gf);`,
  'global let not on window': `let gl = 1; log(window.gl); const gc = 2; log('gc' in window);`,
  'implicit global': `function f(){ implicitG = 7; } f(); log(implicitG, window.implicitG);`,
  'strict undeclared assign': `'use strict'; try { undeclaredZ = 1; } catch (e) { logError(e); }`,
  'undeclared read': `try { log(notDefinedAnywhere); } catch (e) { logError(e); } log(typeof notDefinedAnywhere);`,
  'typeof variants': `let a; log(typeof a, typeof 1, typeof 's', typeof true, typeof null, typeof {}, typeof [], typeof function(){}, typeof Symbol(), typeof 1n, typeof undefined);`,
  'delete': `var o = {a: 1, b: 2}; log(delete o.a, o.a, 'a' in o, Object.keys(o)); let v = 1; log(delete v); log(delete 1);`,
  'arguments strict': `function f(a){ 'use strict'; a = 2; return [arguments.length, arguments[0], a]; } log(f(1, 2, 3));`,
  'arguments sloppy mapped': `function f(a){ arguments[0] = 9; return a; } log(f(1)); function g(a){ a = 7; return arguments[0]; } log(g(1));`,
  'arguments in arrow': `function f(){ const g = () => arguments[0]; return g(); } log(f('outer'));`,
  'rest params': `function f(a, ...r){ return [a, r.length, r]; } log(f(1, 2, 3)); log(f());`,
  'spread call': `function f(a, b, c){ return a + b + c; } const xs = [1, 2, 3]; log(f(...xs)); log(Math.max(...xs, 10)); log([...'héllo'].length, [...new Set([1,1,2])]);`,
  'sequence and comma': `let a = (1, 2, 3); log(a); for (var i = 0, j = 10; i < j; i += 3, j -= 3); log(i, j);`,
  // ---------- numbers ----------
  'arithmetic': `log(1 + 2, 7 - 10, 3 * 4, 7 / 2, 7 % 3, -7 % 3, 2 ** 10, 2 ** -1, 0 / 0, 1 / 0, -1 / 0, 5 % 0);`,
  'number edge cases': `log(0.1 + 0.2, -0, 0 * -1, Object.is(-0, 0 * -1), NaN === NaN, Number.MAX_SAFE_INTEGER + 2, 1e21, 1e-7, 123456789012345680000);`,
  'int32 ops': `log(5 & 3, 5 | 3, 5 ^ 3, ~5, 1 << 31, -1 >>> 0, -16 >> 2, -16 >>> 28, 2 ** 32 | 0, 4294967297 | 0, 1.9 | 0, -1.9 | 0, NaN | 0, Infinity | 0);`,
  'shift counts': `log(1 << 32, 1 << 33, 8 >> 33, -1 >>> 32, 1 << -1);`,
  'update ops': `let a = 1; log(a++, a, ++a, a--, --a, a); let s = '5'; s++; log(s, typeof s); let o = {n: 1}; o.n++; ++o.n; log(o.n); let arr = [1]; arr[0] += 5; arr[0] *= 2; log(arr[0]);`,
  'compound assign': `let x = 10; x += 5; x -= 3; x *= 2; x /= 4; x %= 4; x **= 3; x <<= 2; x >>= 1; x >>>= 0; x |= 1; x &= 7; x ^= 2; log(x);`,
  'numeric loops sum': `let s = 0; for (let i = 0; i < 1000; i++) s += i * i; log(s); let p = 1; for (let i = 1; i < 20; i++) p *= i; log(p);`,
  'float accumulation': `let s = 0; for (let i = 0; i < 100; i++) s += 0.1; log(s); let h = 0; for (let i = 0; i < 100; i++) h = (h * 31 + i) | 0; log(h);`,
  'hash loop': `function hashLoop(n){ let x = 123456789; for (let i = 0; i < n; i++) { x ^= x << 13; x ^= x >>> 17; x ^= x << 5; } return x >>> 0; } log(hashLoop(1000));`,
  'math intrinsics': `log(Math.sqrt(2), Math.abs(-3), Math.floor(-1.5), Math.ceil(1.2), Math.round(2.5), Math.round(-2.5), Math.trunc(-4.7), Math.min(3, 1, 2), Math.max(), Math.min(), Math.sign(-3), Math.hypot(3, 4), Math.fround(5.5), Math.imul(3, 4), Math.clz32(1));`,
  'math trig': `log(Math.sin(1).toFixed(6), Math.cos(1).toFixed(6), Math.atan2(1, 1).toFixed(6), Math.exp(1).toFixed(6), Math.log(10).toFixed(6), Math.pow(2, 0.5).toFixed(6), Math.PI, Math.E);`,
  'math min max nan': `log(Math.min(1, NaN), Math.max(-0, 0), Object.is(Math.min(0, -0), -0), Math.max('3', 2), Math.abs('-2'), Math.floor(null));`,
  'number methods': `log((3.14159).toFixed(2), (255).toString(16), (255).toString(2), Number('12px'), parseInt('12px'), parseFloat('3.5e2x'), Number.isInteger(5.0), (1234.5678).toPrecision(6), String(1/3));`,
  'number coercions': `log('3' * '4', '3' + 4, 3 + '4', '10' / 2, true + 1, null + 1, undefined + 1, [] + [], [] + {}, [1,2] + 3, '5' - - '2', +'', +' 12 ', +'0x1f', -'abc');`,
  'comparisons': `log(1 < 2, '10' < '9', 10 < 9, '10' < 9, null >= 0, undefined == null, undefined === null, NaN < 1, 'a' < 'b', [2] > 1, 1 == '1', 0 == '', 0 == false, '' == false, null == 0);`,
  'bigint': `log(2n ** 64n, 10n / 3n, -7n % 3n, 1n << 70n, typeof (5n * 3n), 5n == 5, 5n === 5, 3n > 2);`,
  // ---------- strings ----------
  'string basics': `const s = 'Hello, WASM! 😀'; log(s.length, s.charCodeAt(14), s.charAt(1), s[4], s.slice(-6), s.substring(7, 11), s.indexOf('l'), s.lastIndexOf('l'), s.includes('WASM'), s.startsWith('Hell'), s.endsWith('😀'));`,
  'string methods': `const s = '  a,b,,c  '; log(s.trim(), s.split(','), s.toUpperCase(), 'abc'.repeat(3), 'x'.padStart(4, '-'), 'a-b-c'.replace('-', '+'), 'a-b-c'.replaceAll('-', '+'), 'abc'.at(-1), 'ab'.concat('cd', 1));`,
  'string concat loop': `let s = ''; for (let i = 0; i < 50; i++) s += String.fromCharCode(65 + (i % 26)); log(s, s.length); let t = ''; for (const ch of 'привет') t = ch + t; log(t);`,
  'template literals': `const a = 1, b = 'x', o = {toString(){ return 'O'; }}; log(\`a=\${a} b=\${b} o=\${o} n=\${null} u=\${undefined} arr=\${[1,2]}\`);`,
  'tagged template': `function tag(strings, ...vals){ return strings.raw.join('|') + '#' + vals.join(','); } log(tag\`a\${1}b\${2}c\\n\`);`,
  'string compare and sort': `log(['b', 'a', 'C', 'ä'].sort(), 'a' < 'B', 'abc'.localeCompare('abd'), ['10', '9', '1'].sort());`,
  'string escapes and unicode': `const s = 'tab\\tnl\\nq\\'u\\u00e9\\u{1F600}'; log(JSON.stringify(s), s.length, [...s].length, s.codePointAt(10), String.fromCodePoint(128512));`,
  'regex': `const r = /(\\d+)-(\\w+)/g; const s = '12-ab 34-cd'; log(s.match(r), s.replace(r, '$2:$1'), r.test('5-x'), [...s.matchAll(/\\d+/g)].map(m => m[0] + '@' + m.index), 'a1b2'.split(/\\d/));`,
  'json': `const o = {a: 1, b: [1, 'x', null, true], c: {d: undefined, e: 1.5}}; const s = JSON.stringify(o); log(s); const p = JSON.parse(s); log(p.b[1], p.c.e, Object.keys(p.c)); log(JSON.stringify({k: [new Date(0)]}), JSON.stringify('é\\n'));`,
  // ---------- objects ----------
  'object literal': `const k = 'dyn'; const o = {a: 1, 'b c': 2, [k + 1]: 3, 4: 'four', m(){ return this.a; }, get g(){ return this.a * 10; }, set g(v){ this.a = v; }}; log(o.a, o['b c'], o.dyn1, o[4], o.m(), o.g); o.g = 5; log(o.a, Object.keys(o));`,
  'object key order': `const o = {b: 1, a: 2, 2: 'x', 1: 'y'}; o.c = 3; o[0] = 'z'; delete o.a; o.a = 4; log(Object.keys(o), JSON.stringify(o));`,
  'object spread rest': `const a = {x: 1, y: 2}; const b = {...a, y: 3, z: 4}; const {x, ...rest} = b; log(b, x, rest); log({...null, ...'hi', ...[9]});`,
  'object methods': `const o = {a: 1, b: 2}; log(Object.entries(o), Object.values(o), Object.assign({}, o, {c: 3}), Object.fromEntries([['k', 1]]), Object.hasOwn(o, 'a'), o.hasOwnProperty('b'), 'toString' in o);`,
  'property shapes': `function P(x){ return {x, y: x * 2}; } const ps = []; for (let i = 0; i < 5; i++) ps.push(P(i)); ps[2].z = 'extra'; log(ps.map(p => p.x + p.y).join(), ps[2], ps[3].z);`,
  'object as dictionary': `const d = {}; for (let i = 0; i < 20; i++) d['k' + (i % 7)] = (d['k' + (i % 7)] || 0) + i; log(d); log(Object.keys(d).length);`,
  'nested objects': `const world = {chunks: {}, player: {pos: {x: 1, y: 2, z: 3}}}; world.chunks['0,0'] = {blocks: [1, 2, 3]}; world.player.pos.x += 10; log(world.player.pos, world.chunks['0,0'].blocks.length, world.chunks['1,1']);`,
  'property on primitives': `log('abc'.length, (5).constructor.name, true.toString(), 'x'.constructor === String); try { null.x; } catch (e) { logError(e); } try { undefined.x = 1; } catch (e) { logError(e); }`,
  'getters setters defineProperty': `const o = {}; let hits = 0; Object.defineProperty(o, 'v', {get(){ hits++; return 42; }, enumerable: false}); log(o.v, o.v, hits, Object.keys(o), JSON.stringify(o)); Object.defineProperty(o, 'ro', {value: 1, writable: false}); o.ro = 2; log(o.ro);`,
  'freeze': `'use strict'; const o = Object.freeze({a: 1}); try { o.a = 2; } catch (e) { logError(e); } log(o.a, Object.isFrozen(o));`,
  'proto chain': `const base = {greet(){ return 'hi ' + this.name; }}; const o = Object.create(base); o.name = 'o'; log(o.greet(), Object.getPrototypeOf(o) === base, 'greet' in o, o.hasOwnProperty('greet')); const lit = {__proto__: base, name: 'lit'}; log(lit.greet());`,
  'this binding': `const o = {v: 1, f(){ return this && this.v; }}; const f = o.f; log(o.f(), f(), f.call({v: 2}), f.apply({v: 3}), f.bind({v: 4})()); function sloppy(){ return this === window; } log(sloppy()); function strict(){ 'use strict'; return this; } log(strict());`,
  'optional chaining': `const o = {a: {b: {c: 1}}, f(){ return 'f'; }}; log(o?.a?.b?.c, o.x?.y.z, o.f?.(), o.g?.(), o?.['a']?.b, (null)?.x); let n = null; log(n?.x.y.z);`,
  'nullish and logical assign': `let a = null, b = 0, c = 'x'; log(a ?? 'd', b ?? 'd', b || 'd', c && 'y'); a ??= 5; b ||= 6; c &&= 7; log(a, b, c); const o = {}; o.k ??= []; o.k.push(1); log(o.k);`,
  'in and instanceof': `const o = {a: undefined}; log('a' in o, 'b' in o, 0 in [1], 3 in [1], [] instanceof Array, {} instanceof Array, new Date() instanceof Date);`,
  'equality objects': `const a = {}, b = {}; log(a === a, a === b, a == b, [1] == 1, [1, 2] == '1,2', null == undefined, NaN == NaN);`,
  'getter on object literal used in loop': `const v = {x: 1, y: 2, get len(){ return Math.sqrt(this.x * this.x + this.y * this.y); }}; let s = 0; for (let i = 0; i < 10; i++) { v.x = i; s += v.len; } log(s.toFixed(4));`,
  // ---------- arrays ----------
  'array basics': `const a = [1, 2, 3]; a.push(4, 5); log(a.length, a.pop(), a.shift(), a, a.indexOf(3), a.includes(4)); a.unshift(0); a.length = 2; log(a); a[5] = 'x'; log(a.length, a);`,
  'array holes': `const a = [1, , 3]; log(a.length, 1 in a, a); const b = []; b[3] = 1; log(b.length, b.indexOf(undefined), b.findIndex(x => x === undefined)); log([, ].length);`,
  'array higher order': `const a = [5, 1, 4, 2, 3]; log(a.map(x => x * 2), a.filter(x => x % 2), a.reduce((s, x) => s + x, 0), a.some(x => x > 4), a.every(x => x > 0), a.find(x => x > 3), [...a].sort((x, y) => x - y), a.slice().reverse(), a.join('-'));`,
  'array methods 2': `const a = [1, [2, [3, [4]]]]; log(a.flat(), a.flat(Infinity), [1, 2, 3].fill(0, 1), Array.from({length: 3}, (_, i) => i * i), Array.of(7, 8), [3, 1, 2].toSorted?.() ?? 'n/a', [1, 2, 3, 4].splice(1, 2), [1,2,3].at(-1), [1,2,3].findLast(x => x < 3));`,
  'array splice mutation': `const a = [1, 2, 3, 4, 5]; const r = a.splice(1, 2, 'a', 'b', 'c'); log(a, r); a.copyWithin(0, 3); log(a);`,
  'array destructuring': `const [a, , b = 5, ...rest] = [1, 2, undefined, 4, 5]; log(a, b, rest); let x = 1, y = 2; [x, y] = [y, x]; log(x, y); const [[p], {q}] = [[1], {q: 2}]; log(p, q);`,
  'object destructuring': `const {a, b: {c = 3} = {}, d: [e] = [9], ...others} = {a: 1, b: {}, f: 6, g: 7}; log(a, c, e, others); function f({x = 1, y} = {}){ return [x, y]; } log(f(), f({y: 2}));`,
  'array large index': `const a = []; a[1000] = 1; log(a.length); const b = [1, 2]; b[2 ** 32 - 2] = 'x'; log(b.length); b.length = 1; log(b);`,
  'array of arrays': `const grid = []; for (let y = 0; y < 3; y++) { const row = []; for (let x = 0; x < 3; x++) row.push(x + y * 3); grid.push(row); } log(grid, grid[1][2], grid.map(r => r.reduce((a, b) => a + b)).join());`,
  'array sort stability': `const items = [{k: 1, v: 'a'}, {k: 0, v: 'b'}, {k: 1, v: 'c'}, {k: 0, v: 'd'}]; items.sort((a, b) => a.k - b.k); log(items.map(i => i.v).join(''));`,
  'array iteration protocols': `const a = ['x', 'y']; for (const [i, v] of a.entries()) log(i, v); log([...a.keys()], [...a.values()]); for (const k in a) log('key', k);`,
  'array length and push loop': `const a = []; for (let i = 0; i < 1000; i++) a.push(i * 2); let s = 0; for (let i = 0; i < a.length; i++) s += a[i]; log(a.length, s, a[999]);`,
  // ---------- typed arrays, Map, Set ----------
  'typed arrays': `const f = new Float32Array(4); f[0] = 1.1; f[1] = 2; log(f[0], f.length, f); const u = new Uint8Array([255, 256, -1, 3.7]); log(u); const i = new Int32Array(3); i[0] = 2 ** 31; i[1] = -5; log(i); const u16 = new Uint16Array(u.buffer.slice(0, 2)); log(u16.length);`,
  'typed array loops': `const n = 64; const vox = new Uint8Array(n); for (let i = 0; i < n; i++) vox[i] = (i * 7) & 3; let c = 0; for (let i = 0; i < n; i++) if (vox[i] === 2) c++; log(c); const f = new Float32Array(8); for (let i = 0; i < 8; i++) f[i] = i / 3; let s = 0; for (let i = 0; i < 8; i++) s += f[i]; log(s.toFixed(5));`,
  'typed array methods': `const a = new Int16Array([5, -3, 9, 1]); log(a.slice(1, 3), a.subarray(2), Array.from(a.map(x => x * 2)), a.indexOf(9), a.reduce((s, x) => s + x)); a.set([7, 7], 2); log(a); a.sort(); log(a); log(new Uint32Array(new ArrayBuffer(8)).length);`,
  'typed array out of bounds': `const a = new Uint8Array(2); a[5] = 1; log(a[5], a.length, a[-1]); a['1'] = 9; log(a[1]);`,
  'map set': `const m = new Map([[1, 'a']]); m.set('k', {v: 1}).set(NaN, 'nan'); log(m.size, m.get(1), m.get('k').v, m.get(NaN), m.has(2)); m.delete(1); log([...m.keys()]); const s = new Set([3, 1, 3]); s.add(2); log(s.size, [...s], s.has(3)); for (const [k, v] of m) log(k, v);`,
  'map heavy loop': `const m = new Map(); for (let i = 0; i < 200; i++) { const k = 'c' + (i % 17); m.set(k, (m.get(k) || 0) + 1); } log(m.size, m.get('c0'), m.get('c16'));`,
  'weakmap symbol': `const wm = new WeakMap(); const k = {}; wm.set(k, 1); log(wm.get(k), wm.has({})); const sym = Symbol('s'); const o = {[sym]: 1}; log(o[sym], Object.keys(o).length, sym.description);`,
  // ---------- control flow ----------
  'if else chains': `function cls(n){ if (n < 0) return 'neg'; else if (n === 0) return 'zero'; else if (n < 10) return 'small'; return 'big'; } log([-1, 0, 5, 50].map(cls).join());`,
  'switch': `function s(x){ let r = ''; switch (x) { case 1: r += 'a'; case 2: r += 'b'; break; case '3': r += 'c'; break; default: r += 'd'; case 4: r += 'e'; } return r; } log(s(1), s(2), s('3'), s(3), s(4), s(9));`,
  'switch lexical': `function f(x){ switch (x) { case 0: let y = 'zero'; return y; case 1: try { return y; } catch (e) { return e.name; } } } log(f(0), f(1));`,
  'labeled loops': `let out = []; outer: for (let i = 0; i < 4; i++) { for (let j = 0; j < 4; j++) { if (j === 2) continue outer; if (i === 3) break outer; out.push(i + ':' + j); } } log(out.join(' ')); blk: { out = 'in'; break blk; } log(out);`,
  'while do-while': `let i = 0, s = ''; while (i < 5) { if (i === 3) { i++; continue; } s += i++; } do { s += '!'; } while (false); log(s);`,
  'for in object': `const o = {a: 1, b: 2}; const p = Object.create(o); p.c = 3; const keys = []; for (const k in p) keys.push(k); log(keys.join()); for (var k in {x: 1}); log(k);`,
  'for of string and iterators': `let s = ''; for (const ch of 'a😀b') s += '[' + ch + ']'; log(s); const it = {from: 1, to: 3, [Symbol.iterator](){ let c = this.from, t = this.to; return {next: () => c <= t ? {value: c++, done: false} : {value: undefined, done: true}}; }}; log([...it]);`,
  'iterator close on break': `const it = {[Symbol.iterator](){ let i = 0; return {next(){ return {value: i++, done: false}; }, return(){ log('closed'); return {}; }}; }}; for (const v of it) { if (v > 1) break; } try { for (const v of it) throw new Error('x'); } catch (e) { log(e.message); }`,
  'try catch finally': `function f(){ try { return 'try'; } finally { log('finally'); } } log(f()); function g(){ try { throw new Error('e'); } catch (e) { return 'caught ' + e.message; } finally { log('g-fin'); } } log(g()); function h(){ try { return 1; } finally { return 2; } } log(h());`,
  'finally with break continue': `let s = ''; for (let i = 0; i < 4; i++) { try { if (i === 1) continue; if (i === 3) break; s += i; } finally { s += 'f'; } } log(s);`,
  'nested try rethrow': `function f(){ try { try { throw new TypeError('inner'); } finally { log('inner fin'); } } catch (e) { log(e.name, e.message); throw new RangeError('outer'); } } try { f(); } catch (e) { logError(e); log(e.message); }`,
  'throw non errors': `try { throw 42; } catch (e) { log(typeof e, e); } try { throw {code: 7}; } catch ({code}) { log(code); } try { throw null; } catch (e) { log(e); }`,
  'error types from runtime': `try { null.f(); } catch (e) { logError(e); } try { (void 0)(); } catch (e) { logError(e); } try { new (function(){ return 1; }); log('ok'); } catch (e) { logError(e); } try { [].reduce((a, b) => a); } catch (e) { logError(e); } try { new Array(-1); } catch (e) { logError(e); }`,
  'error objects': `const e = new Error('m'); log(e.message, e instanceof Error, String(e)); class MyErr extends Error { constructor(m){ super(m); this.name = 'MyErr'; } } try { throw new MyErr('boom'); } catch (x) { log(x.name, x.message, x instanceof MyErr, x instanceof Error); }`,
  'recursion': `function fib(n){ return n < 2 ? n : fib(n - 1) + fib(n - 2); } log(fib(20)); function depth(n){ return n === 0 ? 0 : 1 + depth(n - 1); } log(depth(2000)); const fact = n => n <= 1 ? 1 : n * fact(n - 1); log(fact(15));`,
  'mutual recursion': `function isEven(n){ return n === 0 ? true : isOdd(n - 1); } function isOdd(n){ return n === 0 ? false : isEven(n - 1); } log(isEven(100), isOdd(7));`,
  'conditional and logical values': `log(0 || null || 'x', 1 && 0 && 2, !!'' , !'0', [] ? 'arr truthy' : 'no', 0 ? 1 : NaN ? 2 : 3, null ?? undefined ?? 0);`,
  // ---------- functions ----------
  'function properties': `function f(a, b = 1, ...c){} log(f.name, f.length, (() => {}).name, (function(){}).name); const o = {m(){}, ['x' + 1]: () => {}}; log(o.m.name, o.x1.name); f.custom = 5; log(f.custom);`,
  'call apply bind': `function f(a, b){ return [this && this.k, a, b]; } log(f.call({k: 1}, 2, 3), f.apply({k: 4}, [5, 6])); const g = f.bind({k: 7}, 8); log(g(9), g.name, g.length);`,
  'higher order functions': `const compose = (...fs) => x => fs.reduceRight((v, f) => f(v), x); const inc = x => x + 1, dbl = x => x * 2; log(compose(inc, dbl)(5), [1, 2, 3].map(compose(dbl, inc)));`,
  'callbacks from host': `const a = [3, 1, 2]; a.sort(function(x, y){ return y - x; }); log(a); log(JSON.stringify({a: 1, b: [2]}, (k, v) => typeof v === 'number' ? v * 10 : v)); log('a-b'.replace(/-/, m => '[' + m + ']'));`,
  'function returning functions in loop': `function makeAdders(n){ const r = []; for (let i = 0; i < n; i++) r.push(x => x + i); return r; } log(makeAdders(4).map(f => f(10)).join());`,
  'iife and closures state': `const counter = (function(){ let c = 0; return function(){ return ++c; }; })(); counter(); counter(); log(counter());`,
  'arguments length and defaults': `function f(a, b = 2){ return arguments.length + ':' + a + ':' + b; } log(f(), f(1), f(1, undefined), f(1, null));`,
  'new target and constructors': `function F(x){ if (!new.target) return 'call'; this.x = x; } log(F(1), new F(2).x); function G(){ return {replaced: true}; } log(new G().replaced); function H(){ this.a = 1; } H.prototype.get = function(){ return this.a; }; log(new H().get(), new H() instanceof H);`,
  // ---------- classes ----------
  'class basics': `class A { constructor(x){ this.x = x; } get double(){ return this.x * 2; } set double(v){ this.x = v / 2; } inc(){ this.x++; return this; } static make(){ return new A(10); } } const a = new A(1); a.inc().inc(); log(a.x, a.double); a.double = 20; log(a.x, A.make().x, typeof A, A.name);`,
  'class inheritance': `class Shape { constructor(n){ this.n = n; } area(){ return 0; } toString(){ return this.n + ':' + this.area(); } } class Rect extends Shape { constructor(w, h){ super('rect'); this.w = w; this.h = h; } area(){ return this.w * this.h; } } class Sq extends Rect { constructor(s){ super(s, s); this.n = 'sq'; } describe(){ return 'I am ' + super.toString(); } } const s = new Sq(3); log(String(new Rect(2, 3)), s.describe(), s instanceof Shape, Object.getPrototypeOf(Sq) === Rect);`,
  'class fields and private': `class C { #secret = 42; static count = 0; pub = 'p'; #m(){ return this.#secret; } constructor(){ C.count++; } reveal(){ return this.#m(); } static has(o){ return #secret in o; } } const c = new C(); new C(); log(c.reveal(), C.count, c.pub, C.has(c), C.has({}), Object.keys(c));`,
  'class static block and accessors': `class K { static #n = 1; static { K.init = K.#n + 1; } static get n(){ return K.#n; } } log(K.init, K.n);`,
  'class methods non enumerable': `class A { m(){} } log(Object.keys(A.prototype), Object.getOwnPropertyNames(A.prototype)); try { A(); } catch (e) { logError(e); }`,
  'class extends builtin': `class MyArr extends Array { sum(){ return this.reduce((a, b) => a + b, 0); } } const m = MyArr.from([1, 2, 3]); log(m.sum(), m.length, m instanceof Array); class M2 extends Map { getOr(k, d){ return this.has(k) ? this.get(k) : d; } } log(new M2([[1, 2]]).getOr(1, 0), new M2().getOr(1, 'd'));`,
  'vector class math': `class Vec { constructor(x, y, z){ this.x = x; this.y = y; this.z = z; } add(o){ return new Vec(this.x + o.x, this.y + o.y, this.z + o.z); } len(){ return Math.sqrt(this.x * this.x + this.y * this.y + this.z * this.z); } } let v = new Vec(0, 0, 0); const d = new Vec(1, 2, 2); for (let i = 0; i < 10; i++) v = v.add(d); log(v.len(), v.x);`,
  'super property in object literal': `const base = {hi(){ return 'base hi'; }}; const o = {__proto__: base, hi(){ return 'o + ' + super.hi(); }}; log(o.hi());`,
  'class expression and this in callbacks': `const C = class Named { constructor(){ this.items = [1, 2, 3]; } total(){ let t = 0; this.items.forEach(x => { t += x * this.mult(); }); return t; } mult(){ return 2; } }; log(new C().total(), C.name);`,
  // ---------- generators and async ----------
  'generators': `function* g(){ const x = yield 1; log('got', x); try { yield 2; } finally { log('cleanup'); } return 3; } const it = g(); log(JSON.stringify(it.next())); log(JSON.stringify(it.next('a'))); log(JSON.stringify(it.return(9))); log(JSON.stringify(it.next()));`,
  'generator delegation': `function* inner(){ yield 1; yield 2; return 'r'; } function* outer(){ const r = yield* inner(); yield r; yield* [3, 4]; } log([...outer()]);`,
  'infinite generator take': `function* nat(){ let n = 0; while (true) yield n++; } const out = []; for (const n of nat()) { if (n > 5) break; out.push(n); } log(out);`,
  'async await': `async function f(x){ await null; return x * 2; } async function main(){ const a = await f(1); const [b, c] = await Promise.all([f(2), f(3)]); log(a, b, c); try { await Promise.reject(new Error('bad')); } catch (e) { log('caught', e.message); } return 'done'; } window.__done = main().then(v => log(v));`,
  'async ordering': `const order = []; async function a(){ order.push('a1'); await 0; order.push('a2'); } Promise.resolve().then(() => order.push('p')); a(); order.push('sync'); window.__done = new Promise(r => setTimeout(r, 0)).then(() => log(order.join()));`,
  'async generator for await': `async function* ag(){ for (let i = 0; i < 3; i++) { await null; yield i; } } async function main(){ let s = 0; for await (const v of ag()) s += v; for await (const v of [Promise.resolve(5), 6]) s += v; log(s); } window.__done = main();`,
  'promise chains and timers': `window.__done = new Promise(resolve => { setTimeout(() => { log('timeout'); resolve(); }, 5); Promise.resolve(1).then(v => v + 1).then(v => log('then', v)); queueMicrotask(() => log('micro')); });`,
  // ---------- DOM and host interop ----------
  'dom basics': `const app = document.getElementById('app'); const el = document.createElement('span'); el.textContent = 'hi'; el.className = 'c1'; app.appendChild(el); log(app.innerHTML, app.children.length, el.parentNode === app, document.querySelector('.c1').textContent);`,
  'dom events': `const btn = document.getElementById('btn'); let n = 0; btn.addEventListener('click', e => { n++; log('click', e.type, e.target === btn, this === window); }); btn.onclick = function(){ log('onclick', this === btn); }; btn.click(); btn.click(); log(n);`,
  'dom style and attributes': `const d = document.createElement('div'); d.style.width = '10px'; d.setAttribute('data-x', '5'); d.dataset.y = '6'; log(d.style.width, d.getAttribute('data-x'), d.dataset.x, d.outerHTML);`,
  'canvas 2d': `const c = document.createElement('canvas'); c.width = 4; c.height = 4; const ctx = c.getContext('2d'); ctx.fillStyle = '#ff0000'; ctx.fillRect(0, 0, 2, 2); const d = ctx.getImageData(0, 0, 4, 4).data; log(d[0], d[1], d[3], d[4 * 3], d.length);`,
  'webgl2 context': `const c = document.createElement('canvas'); const gl = c.getContext('webgl2'); if (!gl) log('no webgl'); else { const buf = gl.createBuffer(); gl.bindBuffer(gl.ARRAY_BUFFER, buf); const data = new Float32Array([1, 2, 3]); gl.bufferData(gl.ARRAY_BUFFER, data, gl.STATIC_DRAW); log(gl.getBufferParameter(gl.ARRAY_BUFFER, gl.BUFFER_SIZE), gl.getError()); }`,
  'objects passed to host and back': `const o = {a: 1, nested: {b: [1, 2]}}; const copy = JSON.parse(JSON.stringify(o)); o.a = 2; log(copy.a, o.a); const arr = [3, 1, 2]; arr.sort(); log(arr); const m = new Map(); m.set(o, 'obj'); log(m.get(o)); o.nested.b.push(3); log(JSON.stringify(o));`,
  'host mutation visible': `const o = {count: 0}; window.shared = o; window.shared.count = 5; log(o.count); o.count++; log(window.shared.count); const a = [1]; window.sharedArr = a; window.sharedArr.push(2); a.push(3); log(window.sharedArr.length, a);`,
  'localStorage and Date': `try { localStorage.setItem('k', JSON.stringify({v: 1})); log(JSON.parse(localStorage.getItem('k')).v); localStorage.removeItem('k'); } catch (e) { log('no storage'); } const d = new Date(2020, 0, 15, 10, 30); log(d.getFullYear(), d.getMonth(), d.getDate(), d.getHours(), typeof Date.now());`,
  'console and globals': `log(typeof console.log, typeof window, typeof globalThis, globalThis === window, typeof performance.now(), typeof requestAnimationFrame, isNaN('x'), isFinite('5'), encodeURIComponent('a b'), Number.parseFloat === parseFloat);`,
  'requestAnimationFrame loop': `let frames = 0; window.__done = new Promise(resolve => { function tick(){ frames++; if (frames < 3) requestAnimationFrame(tick); else { log('frames', frames); resolve(); } } requestAnimationFrame(tick); });`,
  'workers from blob': `const src = 'onmessage = e => postMessage(e.data * 2);'; const url = URL.createObjectURL(new Blob([src], {type: 'text/javascript'})); const w = new Worker(url); window.__done = new Promise(r => { w.onmessage = e => { log('worker', e.data); w.terminate(); r(); }; w.postMessage(21); });`,
  'transfer typed array to worker': `const w = new Worker(URL.createObjectURL(new Blob(['onmessage = e => postMessage(new Uint8Array(e.data)[1]);']))); const a = new Uint8Array([1, 2, 3]); window.__done = new Promise(r => { w.onmessage = e => { log('got', e.data, a.length); w.terminate(); r(); }; w.postMessage(a.buffer, [a.buffer]); });`,
  // ---------- larger programs ----------
  'particles simulation': `function makeParticles(n){ const ps = []; for (let i = 0; i < n; i++) ps.push({x: i % 100, y: (i * 7) % 100, vx: 1, vy: -1}); return ps; } function step(ps){ for (let i = 0; i < ps.length; i++) { const p = ps[i]; p.x += p.vx * 0.5; p.y += p.vy * 0.5; if (p.x < 0 || p.x > 100) p.vx = -p.vx; if (p.y < 0 || p.y > 100) p.vy = -p.vy; } } const ps = makeParticles(200); for (let f = 0; f < 30; f++) step(ps); let s = 0; for (const p of ps) s += p.x + p.y; log(s);`,
  'voxel mesher': `function mesh(size){ const vox = new Uint8Array(size * size * size); for (let i = 0; i < vox.length; i++) vox[i] = (Math.imul(i, 2654435761) >>> 28) & 1; const out = []; for (let z = 1; z < size - 1; z++) for (let y = 1; y < size - 1; y++) for (let x = 1; x < size - 1; x++) { const i = x + size * (y + size * z); if (!vox[i]) continue; if (!vox[i + 1]) out.push(x, y, z, 0); if (!vox[i - 1]) out.push(x, y, z, 1); if (!vox[i + size]) out.push(x, y, z, 2); } return out; } const o = mesh(12); log(o.length, o.slice(0, 8));`,
  'noise function': `function hash(x, y){ let h = Math.imul(x, 374761393) + Math.imul(y, 668265263) | 0; h = Math.imul(h ^ (h >>> 13), 1274126177); return ((h ^ (h >>> 16)) >>> 0) / 4294967296; } function smooth(t){ return t * t * (3 - 2 * t); } function noise(x, y){ const xi = Math.floor(x), yi = Math.floor(y), xf = x - xi, yf = y - yi; const a = hash(xi, yi), b = hash(xi + 1, yi), c = hash(xi, yi + 1), d = hash(xi + 1, yi + 1); const u = smooth(xf), v = smooth(yf); return a + (b - a) * u + (c - a) * v + (a - b - c + d) * u * v; } let s = 0; for (let y = 0; y < 20; y++) for (let x = 0; x < 20; x++) s += noise(x * 0.37, y * 0.21); log(s.toFixed(8));`,
  'chunk map simulation': `const chunks = new Map(); function key(x, z){ return x + ',' + z; } function getChunk(x, z){ let c = chunks.get(key(x, z)); if (!c) { c = {x, z, blocks: new Uint8Array(16), dirty: true, neighbors: 0}; chunks.set(key(x, z), c); } return c; } for (let x = -2; x <= 2; x++) for (let z = -2; z <= 2; z++) { const c = getChunk(x, z); c.blocks[(x + z) & 15] = 1; } let n = 0; for (const c of chunks.values()) { for (const [dx, dz] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) if (chunks.has(key(c.x + dx, c.z + dz))) c.neighbors++; n += c.neighbors; } log(chunks.size, n, getChunk(0, 0).blocks);`,
  'state machine with closures': `function machine(){ const handlers = {idle: e => e === 'go' ? 'run' : 'idle', run: e => e === 'stop' ? 'idle' : e === 'jump' ? 'air' : 'run', air: e => 'run'}; let state = 'idle'; const hist = []; return {send(e){ state = handlers[state](e); hist.push(state); return this; }, get history(){ return hist.join('>'); }}; } log(machine().send('go').send('jump').send('x').send('stop').history);`,
  'sort numbers objects strings': `const people = [{n: 'Боб', a: 30}, {n: 'Аня', a: 25}, {n: 'Вера', a: 30}]; log(people.sort((x, y) => x.a - y.a || x.n.localeCompare(y.n)).map(p => p.n).join()); log([10, 9, 1, 100].sort(), [10, 9, 1, 100].sort((a, b) => a - b));`,
  'inventory crafting': `const recipes = {plank: {log: 1}, stick: {plank: 2}, torch: {stick: 1, coal: 1}}; const inv = {log: 3, coal: 2}; function can(item){ const r = recipes[item]; return Object.entries(r).every(([k, n]) => (inv[k] || 0) >= n); } function craft(item, out = 1){ if (!can(item)) return false; for (const [k, n] of Object.entries(recipes[item])) inv[k] -= n; inv[item] = (inv[item] || 0) + out; return true; } craft('plank', 4); craft('stick', 4); craft('torch', 4); log(JSON.stringify(inv));`,
  'int32 remainder edge cases': `
function rem(a, b) { return a % b; }
const out = [];
for (let i = -3; i <= 3; i++) for (let j = -2; j <= 2; j++) { const r = (i | 0) % (j | 0); out.push(Object.is(r, -0) ? '-0' : String(r)); }
log(out.join(' '));
let m = -2147483648 | 0, n = -1 | 0; log(Object.is(m % n, -0), (2147483647 | 0) % (2 | 0), m % 7, (m % (m | 0)));
let k = 0; for (let t = 0; t < 250; t++) k += t % 7; log(k, rem(7, 0), rem(-7, 7));`,
};
