#!/usr/bin/env python3
"""Generates UnityPort/.../Core/SourceItemData.g.cs from reference/data/items.json and
reference/data/creative_tabs.json (both dumped from the running reference main.js)."""
import json
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
items = json.load(open(os.path.join(ROOT, 'reference/data/items.json'), encoding='utf-8'))
tabs = json.load(open(os.path.join(ROOT, 'reference/data/creative_tabs.json'), encoding='utf-8'))['tabs']
OUT = os.path.join(ROOT, 'UnityPort/Assets/BlockcraftPort/Core/SourceItemData.g.cs')


def cs_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def arr(t, vals, per=12):
    lines = []
    for i in range(0, len(vals), per):
        lines.append('            ' + ','.join(vals[i:i + per]) + ',')
    return 'new ' + t + '[]\n        {\n' + '\n'.join(lines) + '\n        }'


def port_key(x):
    # All spawn eggs share tex "item_spawn_egg" in main.js (tinted per mob); the port inventory is keyed
    # by string, so each egg gets a unique key.
    return 'item_spawn_egg_' + x['spawnEgg'] if x.get('spawnEgg') else x['tex']


base = items['itemIdBase']
its = sorted(items['items'], key=lambda x: x['id'])
assert [x['id'] for x in its] == list(range(base, base + len(its)))
g = ['// <auto-generated> by tools/codegen/gen_items.py from reference/data/items.json and',
     '// reference/data/creative_tabs.json (values evaluated from the running reference main.js). Do not edit.',
     'namespace BlockcraftPort', '{',
     '    /// <summary>main.js Gn[] items (numeric ids from ItemIdBase). Port item keys are the texture names.</summary>',
     '    public static class SourceItemData', '    {',
     f'        public const int ItemIdBase = {base};',
     f'        public const int Count = {len(its)};',
     '        public static readonly string[] Key = ' + arr('string', [cs_str(x['key']) for x in its], 6) + ';',
     '        /// <summary>Port inventory item key (main.js tex; spawn eggs get item_spawn_egg_<mob>).</summary>',
     '        public static readonly string[] Tex = ' + arr('string', [cs_str(port_key(x)) for x in its], 6) + ';',
     '        /// <summary>main M1[id].spawnEgg: mob type a spawn egg creates (empty for other items).</summary>',
     '        public static readonly string[] SpawnEgg = ' + arr('string', [cs_str(x.get('spawnEgg') or '') for x in its], 6) + ';',
     '        public static readonly string[] NameEn = ' + arr('string', [cs_str(x['en']) for x in its], 6) + ';',
     '        public static readonly string[] NameRu = ' + arr('string', [cs_str(x['ru']) for x in its], 6) + ';',
     '        /// <summary>Tile index of the item icon in the reference block atlas (main.js M[id].icon).</summary>',
     '        public static readonly short[] IconTile = ' + arr('short', [str(x['faces']['icon']) for x in its], 20) + ';',
     '        public static readonly byte[] Stack = ' + arr('byte', [str(x.get('stack', 64)) for x in its], 30) + ';',
     '        static System.Collections.Generic.Dictionary<string, int> byTex;',
     '        /// <summary>Index into the tables for a port item key, or -1.</summary>',
     '        public static int IndexOfTex(string tex)',
     '        {',
     '            if (tex == null) return -1;',
     '            if (byTex == null)',
     '            {',
     '                var d = new System.Collections.Generic.Dictionary<string, int>(Count);',
     '                for (int i = 0; i < Count; i++) d[Tex[i]] = i;',
     '                byTex = d;',
     '            }',
     '            return byTex.TryGetValue(tex, out int v) ? v : -1;',
     '        }',
     '    }', '',
     '    /// <summary>main.js uo[]: creative inventory tabs with their exact entry order (reference numeric ids).</summary>',
     '    public static class SourceCreativeTabs', '    {',
     f'        public const int Count = {len(tabs)};',
     '        public static readonly string[] Key = { ' + ', '.join(cs_str(t['key']) for t in tabs) + ' };',
     '        public static readonly string[] NameEn = { ' + ', '.join(cs_str(t['en']) for t in tabs) + ' };',
     '        public static readonly string[] NameRu = { ' + ', '.join(cs_str(t['ru']) for t in tabs) + ' };',
     '        /// <summary>main eL: tabs shown in the top row (the rest are in the bottom row).</summary>',
     '        public static readonly bool[] Top = { ' + ', '.join('true' if t['top'] else 'false' for t in tabs) + ' };',
     '        /// <summary>main rL(): reference id drawn on each tab button.</summary>',
     '        public static readonly int[] IconSourceId = { ' + ', '.join(str(t['icon']) for t in tabs) + ' };',
     '        public static readonly int[][] Entries =', '        {']
for t in tabs:
    g.append('            ' + arr('int', [str(v) for v in t['entries']], 20).replace('\n', '\n    ') + ',')
g += ['        };', '    }', '}', '']
open(OUT, 'w', encoding='utf-8').write('\n'.join(g))
print('wrote', OUT, len(its), 'items,', len(tabs), 'tabs')
