// <auto-generated> by tools/codegen/gen_blocks.py for the reference atlas (main.js $l()+Av()).
// Tile t sits at column t%16, row t/16 in 16px cells; UVs use the meshWorker N()/v() 0.06px inset.
namespace BlockcraftPort
{
    public readonly struct AtlasRect
    {
        public readonly float U0, V0, U1, V1;
        public AtlasRect(float u0, float v0, float u1, float v1) { U0=u0; V0=v0; U1=u1; V1=v1; }
    }

    public static class AtlasLayout
    {
        public const int AtlasWidth = 256;
        public const int AtlasHeight = 752;
        public const int TileSize = 16;
        public const int Columns = 16;
        public const int TileCount = 752;
        static readonly AtlasRect[] tileRects = BuildTiles();
        static AtlasRect[] BuildTiles()
        {
            var r = new AtlasRect[TileCount];
            for (int t = 0; t < TileCount; t++)
            {
                int x = (t % Columns) * TileSize, y = (t / Columns) * TileSize;
                r[t] = new AtlasRect((x + .06f) / AtlasWidth, 1f - (y + TileSize - .06f) / AtlasHeight,
                                     (x + TileSize - .06f) / AtlasWidth, 1f - (y + .06f) / AtlasHeight);
            }
            return r;
        }
        /// <summary>UV rect of reference atlas tile t (main.js M[id].top/side/... values).</summary>
        public static AtlasRect Tile(int t) => (uint)t < (uint)TileCount ? tileRects[t] : tileRects[0];

        public static readonly AtlasRect Stone = Tile(3); // stone
        public static readonly AtlasRect Dirt = Tile(2); // dirt
        public static readonly AtlasRect GrassBlockSide = Tile(1); // grass_block_side
        public static readonly AtlasRect GrassBlockTop = Tile(0); // grass_block_top
        public static readonly AtlasRect Sand = Tile(5); // sand
        public static readonly AtlasRect Sandstone = Tile(16); // sandstone
        public static readonly AtlasRect RedSand = Tile(54); // red_sand
        public static readonly AtlasRect RedSandstone = Tile(214); // red_sandstone
        public static readonly AtlasRect RedSandstoneTop = Tile(213); // red_sandstone_top
        public static readonly AtlasRect Gravel = Tile(6); // gravel
        public static readonly AtlasRect Bedrock = Tile(17); // bedrock
        public static readonly AtlasRect WaterStill = Tile(12); // water_still
        public static readonly AtlasRect Ice = Tile(15); // ice
        public static readonly AtlasRect PackedIce = Tile(103); // packed_ice
        public static readonly AtlasRect BlueIce = Tile(104); // blue_ice
        public static readonly AtlasRect Snow = Tile(14); // snow
        public static readonly AtlasRect Deepslate = Tile(84); // deepslate
        public static readonly AtlasRect CoalOre = Tile(18); // coal_ore
        public static readonly AtlasRect IronOre = Tile(19); // iron_ore
        public static readonly AtlasRect GoldOre = Tile(20); // gold_ore
        public static readonly AtlasRect DiamondOre = Tile(21); // diamond_ore
        public static readonly AtlasRect Granite = Tile(76); // granite
        public static readonly AtlasRect Diorite = Tile(74); // diorite
        public static readonly AtlasRect Andesite = Tile(72); // andesite
        public static readonly AtlasRect Tuff = Tile(105); // tuff
        public static readonly AtlasRect Clay = Tile(102); // clay
        public static readonly AtlasRect Mud = Tile(293); // mud
        public static readonly AtlasRect MossBlock = Tile(302); // moss_block
        public static readonly AtlasRect MyceliumSide = Tile(295); // mycelium_side
        public static readonly AtlasRect MyceliumTop = Tile(294); // mycelium_top
        public static readonly AtlasRect PodzolSide = Tile(53); // podzol_side
        public static readonly AtlasRect PodzolTop = Tile(52); // podzol_top
        public static readonly AtlasRect Terracotta = Tile(55); // terracotta
        public static readonly AtlasRect OrangeTerracotta = Tile(56); // orange_terracotta
        public static readonly AtlasRect WhiteTerracotta = Tile(57); // white_terracotta
        public static readonly AtlasRect CactusSide = Tile(37); // cactus_side
        public static readonly AtlasRect CactusTop = Tile(38); // cactus_top
        public static readonly AtlasRect OakLog = Tile(7); // oak_log
        public static readonly AtlasRect OakLogTop = Tile(8); // oak_log_top
        public static readonly AtlasRect OakLeaves = Tile(9); // oak_leaves
        public static readonly AtlasRect BirchLog = Tile(29); // birch_log
        public static readonly AtlasRect BirchLogTop = Tile(30); // birch_log_top
        public static readonly AtlasRect BirchLeaves = Tile(31); // birch_leaves
        public static readonly AtlasRect SpruceLog = Tile(32); // spruce_log
        public static readonly AtlasRect SpruceLogTop = Tile(33); // spruce_log_top
        public static readonly AtlasRect SpruceLeaves = Tile(34); // spruce_leaves
        public static readonly AtlasRect JungleLog = Tile(46); // jungle_log
        public static readonly AtlasRect JungleLogTop = Tile(47); // jungle_log_top
        public static readonly AtlasRect JungleLeaves = Tile(48); // jungle_leaves
        public static readonly AtlasRect AcaciaLog = Tile(49); // acacia_log
        public static readonly AtlasRect AcaciaLogTop = Tile(50); // acacia_log_top
        public static readonly AtlasRect AcaciaLeaves = Tile(51); // acacia_leaves
        public static readonly AtlasRect DarkOakLog = Tile(43); // dark_oak_log
        public static readonly AtlasRect DarkOakLogTop = Tile(44); // dark_oak_log_top
        public static readonly AtlasRect DarkOakLeaves = Tile(45); // dark_oak_leaves
        public static readonly AtlasRect CherryPlanks = Tile(208); // cherry_planks
        public static readonly AtlasRect AmethystBlock = Tile(289); // amethyst_block
        public static readonly AtlasRect BuddingAmethyst = Tile(290); // budding_amethyst
        public static readonly AtlasRect DripstoneBlock = Tile(223); // dripstone_block
        public static readonly AtlasRect LavaStill = Tile(441); // lava_still
        public static readonly AtlasRect ShortGrass = Tile(39); // short_grass
        public static readonly AtlasRect Fern = Tile(58); // fern
        public static readonly AtlasRect Dandelion = Tile(40); // dandelion
        public static readonly AtlasRect Poppy = Tile(41); // poppy
        public static readonly AtlasRect DeadBush = Tile(42); // dead_bush
        public static readonly AtlasRect FloweringAzaleaLeaves = Tile(261); // flowering_azalea_leaves
        public static readonly AtlasRect AzaleaLeaves = Tile(260); // azalea_leaves
        public static readonly AtlasRect Allium = Tile(378); // allium
        public static readonly AtlasRect Cornflower = Tile(381); // cornflower
        public static readonly AtlasRect OxeyeDaisy = Tile(383); // oxeye_daisy
        public static readonly AtlasRect AzureBluet = Tile(379); // azure_bluet
        public static readonly AtlasRect LilyOfTheValley = Tile(382); // lily_of_the_valley
        public static readonly AtlasRect PinkTulip = Tile(385); // pink_tulip
        public static readonly AtlasRect OrangeTulip = Tile(384); // orange_tulip
        public static readonly AtlasRect RedTulip = Tile(386); // red_tulip
        public static readonly AtlasRect WhiteTulip = Tile(387); // white_tulip
        public static readonly AtlasRect BlueOrchid = Tile(380); // blue_orchid
        public static readonly AtlasRect BrownMushroom = Tile(389); // brown_mushroom
        public static readonly AtlasRect RedMushroom = Tile(390); // red_mushroom
        public static readonly AtlasRect MushroomStem = Tile(323); // mushroom_stem
        public static readonly AtlasRect BrownMushroomBlock = Tile(321); // brown_mushroom_block
        public static readonly AtlasRect RedMushroomBlock = Tile(322); // red_mushroom_block
        public static readonly AtlasRect BambooStalk = Tile(745); // bamboo_stalk
        public static readonly AtlasRect SugarCane = Tile(402); // sugar_cane
        public static readonly AtlasRect SweetBerryBush = Tile(405); // sweet_berry_bush
        public static readonly AtlasRect CopperOre = Tile(265); // copper_ore
        public static readonly AtlasRect LapisOre = Tile(263); // lapis_ore
        public static readonly AtlasRect RedstoneOre = Tile(262); // redstone_ore
        public static readonly AtlasRect EmeraldOre = Tile(264); // emerald_ore
        public static readonly AtlasRect DeepslateCoalOre = Tile(268); // deepslate_coal_ore
        public static readonly AtlasRect DeepslateCopperOre = Tile(275); // deepslate_copper_ore
        public static readonly AtlasRect DeepslateIronOre = Tile(269); // deepslate_iron_ore
        public static readonly AtlasRect DeepslateGoldOre = Tile(270); // deepslate_gold_ore
        public static readonly AtlasRect DeepslateDiamondOre = Tile(271); // deepslate_diamond_ore
        public static readonly AtlasRect DeepslateLapisOre = Tile(273); // deepslate_lapis_ore
        public static readonly AtlasRect DeepslateRedstoneOre = Tile(272); // deepslate_redstone_ore
        public static readonly AtlasRect DeepslateEmeraldOre = Tile(274); // deepslate_emerald_ore
        public static readonly AtlasRect Calcite = Tile(83); // calcite
        public static readonly AtlasRect Kelp = Tile(403); // kelp
        public static readonly AtlasRect Seagrass = Tile(404); // seagrass
        public static readonly AtlasRect TubeCoralFan = Tile(414); // tube_coral_fan
        public static readonly AtlasRect BrainCoralFan = Tile(406); // brain_coral_fan
        public static readonly AtlasRect BubbleCoralFan = Tile(408); // bubble_coral_fan
        public static readonly AtlasRect FireCoralFan = Tile(410); // fire_coral_fan
        public static readonly AtlasRect HornCoralFan = Tile(412); // horn_coral_fan
        public static readonly AtlasRect TubeCoralBlock = Tile(332); // tube_coral_block
        public static readonly AtlasRect BrainCoralBlock = Tile(324); // brain_coral_block
        public static readonly AtlasRect BubbleCoralBlock = Tile(326); // bubble_coral_block
        public static readonly AtlasRect FireCoralBlock = Tile(328); // fire_coral_block
        public static readonly AtlasRect HornCoralBlock = Tile(330); // horn_coral_block
        public static readonly AtlasRect SeaPickle = Tile(516); // sea_pickle
        public static readonly AtlasRect LilyPad = Tile(515); // lily_pad
        public static readonly AtlasRect SunflowerTop = Tile(501); // sunflower_top
        public static readonly AtlasRect SunflowerBottom = Tile(502); // sunflower_bottom
        public static readonly AtlasRect LilacTop = Tile(503); // lilac_top
        public static readonly AtlasRect LilacBottom = Tile(504); // lilac_bottom
        public static readonly AtlasRect RoseBushTop = Tile(505); // rose_bush_top
        public static readonly AtlasRect RoseBushBottom = Tile(506); // rose_bush_bottom
        public static readonly AtlasRect PeonyTop = Tile(507); // peony_top
        public static readonly AtlasRect PeonyBottom = Tile(508); // peony_bottom
        public static readonly AtlasRect LargeFernTop = Tile(511); // large_fern_top
        public static readonly AtlasRect LargeFernBottom = Tile(512); // large_fern_bottom
        public static readonly AtlasRect CaveVines = Tile(416); // cave_vines
        public static readonly AtlasRect PumpkinSide = Tile(335); // pumpkin_side
        public static readonly AtlasRect PumpkinTop = Tile(334); // pumpkin_top
        public static readonly AtlasRect MelonSide = Tile(341); // melon_side
        public static readonly AtlasRect MelonTop = Tile(340); // melon_top
        public static readonly AtlasRect OakPlanks = Tile(10); // oak_planks
        public static readonly AtlasRect SprucePlanks = Tile(36); // spruce_planks
        public static readonly AtlasRect Cobblestone = Tile(4); // cobblestone
        public static readonly AtlasRect Glass = Tile(11); // glass
        public static readonly AtlasRect OakTrapdoor = Tile(130); // oak_trapdoor
        public static readonly AtlasRect Ladder = Tile(123); // ladder
        public static readonly AtlasRect Torch = Tile(122); // torch
        public static readonly AtlasRect Rail = Tile(600); // rail
        public static readonly AtlasRect RailCorner = Tile(601); // rail_corner
        public static readonly AtlasRect Vine = Tile(513); // vine
        public static readonly AtlasRect GlowLichen = Tile(514); // glow_lichen
        public static readonly AtlasRect FlowerPot = Tile(598); // flower_pot
        public static readonly AtlasRect IronBars = Tile(470); // iron_bars
        public static readonly AtlasRect BirchPlanks = Tile(35); // birch_planks
        public static readonly AtlasRect BirchDoorTop = Tile(128); // birch_door_top
        public static readonly AtlasRect BirchDoorBottom = Tile(129); // birch_door_bottom
        public static readonly AtlasRect ChestTop = Tile(426); // chest_top
        public static readonly AtlasRect ChestSide = Tile(427); // chest_side
        public static readonly AtlasRect ChestFront = Tile(429); // chest_front
        public static readonly AtlasRect ChestFrontL = Tile(430); // chest_front_l
        public static readonly AtlasRect ChestFrontR = Tile(431); // chest_front_r
        public static readonly AtlasRect ChestTopL = Tile(432); // chest_top_l
        public static readonly AtlasRect ChestTopR = Tile(433); // chest_top_r
        public static readonly AtlasRect BedFootTop = Tile(518); // bed_foot_top
        public static readonly AtlasRect BedHeadTop = Tile(521); // bed_top
        public static readonly AtlasRect BedSide = Tile(519); // bed_side
        public static readonly AtlasRect CraftingTableTop = Tile(420); // crafting_table_top
        public static readonly AtlasRect CraftingTableFront = Tile(421); // crafting_table_front
        public static readonly AtlasRect FurnaceTop = Tile(423); // furnace_top
        public static readonly AtlasRect FurnaceFront = Tile(424); // furnace_front
        public static readonly AtlasRect FurnaceFrontOn = Tile(445); // furnace_front_on
        public static readonly AtlasRect Farmland = Tile(434); // farmland
        public static readonly AtlasRect FarmlandMoist = Tile(447); // farmland_moist
        public static readonly AtlasRect Wheat0 = Tile(437); // wheat_stage0
        public static readonly AtlasRect Wheat1 = Tile(438); // wheat_stage2
        public static readonly AtlasRect Wheat2 = Tile(439); // wheat_stage4
        public static readonly AtlasRect Wheat3 = Tile(440); // wheat_stage7
        public static readonly AtlasRect Fire = Tile(458); // fire
        public static readonly AtlasRect Cobweb = Tile(467); // cobweb
        public static readonly AtlasRect TntSide = Tile(26); // tnt_side
        public static readonly AtlasRect TntTop = Tile(27); // tnt_top
        public static readonly AtlasRect TntBottom = Tile(28); // tnt_bottom
        public static readonly AtlasRect CutSandstone = Tile(211); // cut_sandstone
        public static readonly AtlasRect ChiseledSandstone = Tile(212); // chiseled_sandstone
        public static readonly AtlasRect BlueTerracotta = Tile(199); // blue_terracotta
        public static readonly AtlasRect DarkOakPlanks = Tile(204); // dark_oak_planks
        public static readonly AtlasRect Netherrack = Tile(88); // netherrack
        public static readonly AtlasRect Magma = Tile(305); // magma
        public static readonly AtlasRect Obsidian = Tile(23); // obsidian
        public static readonly AtlasRect CryingObsidian = Tile(314); // crying_obsidian
        public static readonly AtlasRect GoldBlock = Tile(283); // gold_block
        public static readonly AtlasRect OakDoorTop = Tile(124); // oak_door_top
        public static readonly AtlasRect OakDoorBottom = Tile(125); // oak_door_bottom
        public static readonly AtlasRect Bricks = Tile(13); // Bricks
        public static readonly AtlasRect RedWool = Tile(60); // RedWool
        public static readonly AtlasRect OakSapling = Tile(396); // oak_sapling
        public static readonly AtlasRect BirchSapling = Tile(398); // birch_sapling
        public static readonly AtlasRect SpruceSapling = Tile(397); // spruce_sapling
        public static readonly AtlasRect JungleSapling = Tile(399); // jungle_sapling
        public static readonly AtlasRect AcaciaSapling = Tile(400); // acacia_sapling
        public static readonly AtlasRect DarkOakSapling = Tile(401); // dark_oak_sapling
    }
}
